### PR TITLE
Enable mouse support in clock example

### PR DESCRIPTION
**Pull request by avysk**
Adds mouse support in clock example for #98

### CODE REVIEW

**Comment by avysk** [comment]
@jeremiedimino I didn't contribute to this for 7 years, so I'd appreciate a review of this and #101 even though the patches are small.

**Comment by avysk** [comment]
> @jeremiedimino I didn't contribute to this for 7 years, so I'd appreciate a review of this and #101 even though the patches are small.

...or, maybe, judging by the commit history, @kandu can have a look?

**Comment by avysk** [comment]
It seems that this and #101 failed because of some Travis problem with doing os x build, not because of the changes. Maybe someone can re-run it?

**Comment by pmetzger** [comment]
I wouldn't worry much about the CI issues; we need to switch to a new CI soon anyway.

**Comment by avysk** [comment]
This (and #101) are very small and quite straightforward; any chance to get a review?

**Comment by pmetzger** [comment]
@kandu Can you review this? It's very small. If not, I will just merge it.

**Pull request merged**
