### PR TITLE
CI: macOS both x86 and arm

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by pmetzger** [comment]
@liyishuai You should feel free to commit this if it works correctly.

**Comment by liyishuai** [comment]
> ERROR: Permission to ocaml-community/lambda-term.git denied to liyishuai.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by pmetzger** [comment]
I thought I had given you permissions across ocaml-community. Let's check that.

**Comment by pmetzger** [comment]
It seems you did not accept your team invitation. Please accept it.

**Pull request merged**
