### PR TITLE
LTerm_read_line: vi mode

### LINKED ISSUE #13: feature request: vim edit mode
it would be great to have a vi editing mode to the extent that readline provides it. this would remove the last nitpick i have about utop compared to rlwrap ocaml

### PR DESCRIPTION
**Pull request by kandu**
LTerm_read_line: add new vi edit mode. resolve #13
This PR depends on ocaml-community/zed/pull/38

### CODE REVIEW

**Comment by kandu** [comment]
The logic is fairly simple.
The mew_vi generated modal editing engine has only one entry and one exit.
In the event loop of lterm_read_line,  we feed key events to the entry and get vi actions from the exit. Then use LTerm_vi to translate the actions to zed actions and feed the zed actions to the original event loop. Ok, done.
It breaks the backward-compatibility only a little bit so that a <how to upgrade to lambda-term 3> guide is even not needed. We may just mention it in the CHANGES file.

**Comment by nilsbecker** [comment]
i was able to install utop 2.5.0~ following the instructions. it runs fine. i tried basic editing. so far i found one motion that is recognized by readline but not recognized by lterm: `^`.

**Comment by nilsbecker** [comment]
just for my information: what is the scope of the vi features that are supposed to work? exactly what readline does? more? less? full vim ;)?

**Comment by nilsbecker** [comment]
some more observations:

`dw` works in both lterm and readline
`yw` works in readline, not in lterm
`yiw` works in neither but would be nice to have 
`diw` as above
`da` is echoed as modifiers but e.g. `daw` did not work in lterm

multiline commands:
`gj` and `gk` would be nice to have to move in the same column between lines
`J` for line joining would be nice to have. 
(i think these go beyond readline but would be very usefule for utop where multiline input is common)
`p` of a `dd` deleted line mixes up line breaks
`P` of lines seems to work better
`yy` does not seem to work
it is difficult to tell if a line has been wrapped or if there is a genuine line break -- both look the same.

**Comment by nilsbecker** [comment]
`;` for repeating a search does not work. then `,` for the other direction would be nice too.
`/` and `?` are not implemented but may be less important?
wow, `%` works! cool.
`m` marks are missing but may be out of scope
`.` for repeat missing, may be out of scope
`>` and `<` might be worthwhile for indenting lines
`C` and `D` might be worthwhile but can be replaced by `c$` and `d$`
`t` and `T` would be good in addition to `f` and `F`
i just learned that `Y` does the same as `yy`

anyway, now i'm through with my scan of https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html. 

great work, it's useful already now!

a last comment: in UTop it would be nice to have a simple command (shift-enter?) that does `GA;;<esc><cr>`

**Comment by kandu** [comment]
Ah, thank you! @nilsbecker. It's so exhaustive that I'll take it as a formal to-do and technical list.

> just for my information: what is the scope of the vi features that are supposed to work? exactly what readline does? more? less? full vim ;)?
In fact, I had no plan what should be implemented before your feedback. I wanted to see the feasibility of mew and mew_vi first. After look into your great feedback, I think it's now proved.

> some more observations:
> 
> `dw` works in both lterm and readline
> `yw` works in readline, not in lterm
> `yiw` works in neither but would be nice to have
> `diw` as above
> `da` is echoed as modifiers but e.g. `daw` did not work in lterm

`y` `aw` `iw` were not implemented, so all the combinations containing any of them did not work, but you'll see them in the next update

> `J` for line joining would be nice to have.

Yeah, it's coming.

> `p` of a `dd` deleted line mixes up line breaks
> `P` of lines seems to work better
> `yy` does not seem to work

This is because vi records extra info about the content in a register, that is, distinguish an entire line and a sequence of chars(whether contains \n or not). When it's going to paste an entire line, it makes a new blank line first and then paste the stripped string into it. For now, LTerm\_vi is using the default zed clipboard, which only records the sequence of chars. To resolve this glitch, we'll make our own register, content data type and alter the logic a bit.
`yy`, the `y` issue will be resolved in the next update as mentioned above.

> `;` for repeating a search does not work. then `,` for the other direction would be nice too.
> `/` and `?` are not implemented but may be less important?

Ok, we'll see them in the **next next** update.


> `>` and `<` might be worthwhile for indenting lines

Yeah, It seems we better support config files, so users can config the indent width, and other customizable settings.

> `C` and `D` might be worthwhile but can be replaced by `c$` and `d$`
> `t` and `T` would be good in addition to `f` and `F`

It's easy to implement, just add some aliases.

> great work, it's useful already now!

Yours is great, too.

> anyway, now i'm through with my scan of https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html. 
> a last comment: in UTop it would be nice to have a simple command (shift-enter?) that does `GA;;<esc><cr>`

Good idea, I'd like to hear more opinion about this, because it's an `enter` related shortcut, we'll make sure it's conflict-free.

Thanks again, @nilsbecker :smile:

**Comment by nilsbecker** [comment]
> Yeah, It seems we better support config files, so users can config the indent width, and other customizable settings.

Config files would be neat but I think it would also be a step up in complexity? There is also a point to be made for keeping it simple, at least initially.

I think I have found a bug: For me (macos, iTerm2 and Terminal.app) in vi-enabled UTop, when i press <c-c> at the prompt and then some commands, e.g. `b b b` they get echoed above the line and after 6 of them UTop hangs. I can't kill it using any of <c-c>, <c-d> or <c-z> .

**Comment by nilsbecker** [comment]
Another thing: I think `r` is also missing?

**Comment by kandu** [comment]
Hi @diml, 
> a last comment: in UTop it would be nice to have a simple command (shift-enter?) that does GA;;<esc><cr>

Are there any potential conflicts? e.g. when within emacs or other keybindings? If there is none, maybe we'll implement it?

**Comment by diml** [comment]
That should be fine. FTR, you can already bind such a command by adding this to your init file:

```
       LTerm_read_line.bind
         [ { control = false; meta = false; shift = true; code = Enter } ]
         [ UTop.end_and_accept_current_phrase ]
```

The only reason it is not an edition action that you can bind like other actions via the inputrc file is because it is utop specific action and so lambda-term doesn't know about it.

**Comment by kandu** [comment]
I just make a quick testing, on both cli and gui terminal, only alt-enter works, the modifier of ctrl-enter or shift-enter was missing.

The hanging bug is resolved and all the to-do items in the **next** update list are done(some updates are in the mew_vi and zed projects so they didn't show up in the commits history here).

I think it's time to push the trigger, release them all.

**Comment by kandu** [comment]
> Another thing: I think `r` is also missing?

It's like go fishing by a small pool, I won't catch all the fishes away. Some fishes are left for the contributors ;)

**Pull request merged**
